import { v4 as uuidv4, v5 as uuidv5 } from 'uuid';
import { supabaseAdmin } from '../database/supabaseAdmin.ts';

const NAMESPACE = '6ba7b810-9dad-11d1-80b4-00c04fd430c8';

export interface CheckpointOption {
  id: string;
  option_text: string;
  is_correct: boolean;
  display_order: number;
}

export interface LessonCheckpoint {
  id: string;
  lesson_id: string;
  question: string;
  question_type: string;
  explanation: string;
  options: CheckpointOption[];
}

export interface StudentAttempt {
  id: string;
  user_id: string;
  checkpoint_id: string;
  selected_option_id: string;
  is_correct: boolean;
  attempted_at: string;
}

// In-memory persistent store for attempts
const attemptsStore: StudentAttempt[] = [];

// Reference Video Lesson ID
const refLessonId = 'f0206c01-0200-0000-0000-000000000000';

// 44 Checkpoint definitions (43 ARTICLE + 1 VIDEO)
const rawCheckpoints: { lesson_id: string; question: string; explanation: string; options: { text: string; is_correct: boolean }[] }[] = [
  // Module 1
  {
    lesson_id: refLessonId,
    question: 'Why is statistics critical in modern data analytics and business decision making?',
    explanation: 'Statistics provides quantitative methods to distinguish genuine data patterns (signals) from random variations (noise).',
    options: [
      { text: 'It provides a formal system to differentiate true signals from random noise in data.', is_correct: true },
      { text: 'It replaces the need for domain knowledge and business intuition completely.', is_correct: false },
      { text: 'It guarantees 100% accuracy in all future predictions.', is_correct: false },
      { text: 'It is only required when working with small datasets under 100 rows.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c01-0300-0000-0000-000000000000',
    question: 'What is the main difference between descriptive and inferential statistics?',
    explanation: 'Descriptive statistics organizes and summarizes observed data, whereas inferential statistics uses sample evidence to estimate population properties.',
    options: [
      { text: 'Descriptive statistics summarizes sample data, while inferential statistics draws conclusions about a larger population.', is_correct: true },
      { text: 'Descriptive statistics predicts future outcomes, while inferential statistics calculates past averages.', is_correct: false },
      { text: 'Descriptive statistics only uses graphs, while inferential statistics only uses tables.', is_correct: false },
      { text: 'Descriptive statistics applies to populations, while inferential statistics applies only to small samples.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c01-0400-0000-0000-000000000000',
    question: "An analyst surveys 1,000 customers from a company's total 50,000 subscriber base. What represents the sample?",
    explanation: 'A sample is a subset of individuals selected from a larger target population.',
    options: [
      { text: 'The 1,000 surveyed customers', is_correct: true },
      { text: 'The 50,000 total subscribers', is_correct: false },
      { text: 'All e-commerce shoppers nationwide', is_correct: false },
      { text: 'The revenue generated by the company', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c01-0500-0000-0000-000000000000',
    question: 'Which variable is an example of continuous quantitative data?',
    explanation: 'Continuous quantitative data can take any numeric value within an interval, including fractional values.',
    options: [
      { text: 'Exact delivery time in minutes (e.g., 24.35 mins)', is_correct: true },
      { text: 'Customer membership tier (Gold, Silver, Bronze)', is_correct: false },
      { text: 'Number of items in a shopping cart (1, 2, 3)', is_correct: false },
      { text: 'Country of residence (USA, India, UK)', is_correct: false }
    ]
  },

  // Module 2
  {
    lesson_id: 'f0206c02-0100-0000-0000-000000000000',
    question: 'What is the primary purpose of a measure of central tendency?',
    explanation: 'Central tendency metrics (mean, median, mode) summarize a dataset by pinpointing its central location.',
    options: [
      { text: 'To identify a single typical or central value that represents a dataset.', is_correct: true },
      { text: 'To measure how far values are spread out from each other.', is_correct: false },
      { text: 'To determine if a correlation exists between two variables.', is_correct: false },
      { text: 'To test whether a sample mean equals a population mean.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c02-0200-0000-0000-000000000000',
    question: "A tech company's salary dataset contains one multi-millionaire CEO salary. Which measure best represents the typical employee salary?",
    explanation: 'The median is robust to extreme outliers, whereas the mean gets pulled heavily toward extreme values.',
    options: [
      { text: 'Median', is_correct: true },
      { text: 'Mean', is_correct: false },
      { text: 'Variance', is_correct: false },
      { text: 'Standard Deviation', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c02-0500-0000-0000-000000000000',
    question: 'When calculating a course grade where the final exam counts for 50% and homework counts for 50%, which average should be used?',
    explanation: 'A weighted mean accounts for differing levels of importance or relative weights assigned to different data points.',
    options: [
      { text: 'Weighted Mean', is_correct: true },
      { text: 'Arithmetic Mean', is_correct: false },
      { text: 'Mode', is_correct: false },
      { text: 'Geometric Mean', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c02-0700-0000-0000-000000000000',
    question: 'How does adding an extreme high outlier affect the mean and median of a dataset?',
    explanation: 'The arithmetic mean incorporates every value and is sensitive to outliers, while the median remains stable.',
    options: [
      { text: 'Increases the mean, while keeping the median relatively unchanged', is_correct: true },
      { text: 'Increases the median, while keeping the mean unchanged', is_correct: false },
      { text: 'Decreases both the mean and median equally', is_correct: false },
      { text: 'Has no impact on either the mean or median', is_correct: false }
    ]
  },

  // Module 3
  {
    lesson_id: 'f0206c03-0100-0000-0000-000000000000',
    question: 'Two stocks have the same average annual return of 8%. Stock A has a range of 2% to 14%, while Stock B has a range of -15% to 30%. What does this indicate?',
    explanation: 'A wider range indicates greater spread and variability around the central average.',
    options: [
      { text: 'Stock B has higher variability and higher risk than Stock A.', is_correct: true },
      { text: 'Stock A is more profitable than Stock B.', is_correct: false },
      { text: 'Stock B has a higher median than Stock A.', is_correct: false },
      { text: 'Range cannot be used to compare financial variability.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c03-0400-0000-0000-000000000000',
    question: 'Why is standard deviation often preferred over variance when reporting data insights?',
    explanation: 'Variance squares the differences (yielding squared units), whereas taking the square root restores the original measurement units.',
    options: [
      { text: 'Standard deviation is expressed in the same original units as the data.', is_correct: true },
      { text: 'Standard deviation is always negative.', is_correct: false },
      { text: 'Standard deviation eliminates all outliers automatically.', is_correct: false },
      { text: 'Variance cannot be computed for sample data.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c03-0500-0000-0000-000000000000',
    question: 'What percentage of data points fall within the Interquartile Range (IQR)?',
    explanation: 'IQR measures the spread of the middle 50% of values, calculated as Q3 - Q1.',
    options: [
      { text: 'The middle 50% of the dataset', is_correct: true },
      { text: 'The top 25% of the dataset', is_correct: false },
      { text: 'The lower 75% of the dataset', is_correct: false },
      { text: '100% of all data points', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c03-0700-0000-0000-000000000000',
    question: 'Why do data scientists scale features with high dispersion before training distance-based ML models (e.g., KNN)?',
    explanation: 'Features with large scales or variances disproportionately influence distance metrics unless standardized.',
    options: [
      { text: 'To prevent high-variance features from dominating distance calculations.', is_correct: true },
      { text: 'To increase the total number of training rows.', is_correct: false },
      { text: 'To convert categorical variables into numerical values.', is_correct: false },
      { text: 'To eliminate missing values from the dataset.', is_correct: false }
    ]
  },

  // Module 4
  {
    lesson_id: 'f0206c04-0100-0000-0000-000000000000',
    question: 'What does the height of a bar in a standard histogram represent?',
    explanation: 'Histograms display continuous data grouped into bins, where bar height corresponds to the frequency of observations in each bin.',
    options: [
      { text: 'The frequency (or count) of data values falling within that interval/bin.', is_correct: true },
      { text: 'The cumulative total of all preceding bins.', is_correct: false },
      { text: 'The average value of the dataset.', is_correct: false },
      { text: 'The correlation between two numerical variables.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c04-0400-0000-0000-000000000000',
    question: 'In a perfectly symmetrical Normal Distribution, what is true about the mean, median, and mode?',
    explanation: 'Symmetrical bell curves peak at the center where mean, median, and mode coincide.',
    options: [
      { text: 'Mean = Median = Mode', is_correct: true },
      { text: 'Mean > Median > Mode', is_correct: false },
      { text: 'Mean < Median < Mode', is_correct: false },
      { text: 'Mode is always equal to zero', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c04-0600-0000-0000-000000000000',
    question: 'A retail income distribution has a long tail extending toward higher income values to the right. How is this distribution described?',
    explanation: 'Positive skewness means the tail extends toward larger positive values on the right side.',
    options: [
      { text: 'Positively skewed (right-skewed)', is_correct: true },
      { text: 'Negatively skewed (left-skewed)', is_correct: false },
      { text: 'Symmetrical normal distribution', is_correct: false },
      { text: 'Uniform distribution', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c04-0800-0000-0000-000000000000',
    question: 'Under the standard 1.5 x IQR rule, a data point is classified as an outlier if it lies below:',
    explanation: 'Low outliers fall below Q1 - 1.5*IQR, while high outliers rise above Q3 + 1.5*IQR.',
    options: [
      { text: 'Q1 - 1.5 x IQR', is_correct: true },
      { text: 'Q3 + 1.5 x IQR', is_correct: false },
      { text: 'Mean - 1.0 x Standard Deviation', is_correct: false },
      { text: 'Median / 2', is_correct: false }
    ]
  },

  // Module 5
  {
    lesson_id: 'f0206c05-0100-0000-0000-000000000000',
    question: 'What is the valid numerical range for any probability value P(E)?',
    explanation: 'Probabilities are non-negative proportions bounded between 0 (impossible) and 1 (certain).',
    options: [
      { text: '0.0 to 1.0 (or 0% to 100%)', is_correct: true },
      { text: '-1.0 to +1.0', is_correct: false },
      { text: '0 to infinity', is_correct: false },
      { text: 'Any integer value', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c05-0300-0000-0000-000000000000',
    question: 'If Event A and Event B are mutually exclusive, what is the probability that both events occur simultaneously P(A and B)?',
    explanation: 'Mutually exclusive events cannot happen at the same time, so P(A and B) = 0.',
    options: [
      { text: '0', is_correct: true },
      { text: '0.5', is_correct: false },
      { text: 'P(A) + P(B)', is_correct: false },
      { text: '1.0', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c05-0400-0000-0000-000000000000',
    question: 'Flipping a fair coin twice: does the outcome of the first flip affect the outcome of the second flip?',
    explanation: 'Independent events have no memory; the probability of the second event is unaffected by the first.',
    options: [
      { text: 'No, the events are independent.', is_correct: true },
      { text: 'Yes, the events are dependent.', is_correct: false },
      { text: 'Yes, because tails becomes more likely after heads.', is_correct: false },
      { text: 'Only if the coin is flipped more than 10 times.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c05-0600-0000-0000-000000000000',
    question: 'What does the notation P(A | B) represent?',
    explanation: 'P(A | B) denotes conditional probability: the likelihood of A happening under the condition that B is true.',
    options: [
      { text: 'The probability of Event A occurring given that Event B has already occurred.', is_correct: true },
      { text: 'The probability of Event A or Event B occurring.', is_correct: false },
      { text: 'The probability of neither Event A nor Event B occurring.', is_correct: false },
      { text: 'The product of P(A) and P(B).', is_correct: false }
    ]
  },

  // Module 6
  {
    lesson_id: 'f0206c06-0100-0000-0000-000000000000',
    question: 'Which of the following represents a discrete random variable?',
    explanation: 'Discrete random variables take countable whole numbers (0, 1, 2, 3...).',
    options: [
      { text: 'The number of customer returns on an e-commerce platform in a day.', is_correct: true },
      { text: 'The exact temperature of a server room in degrees Celsius.', is_correct: false },
      { text: 'The weight of a shipping container in kilograms.', is_correct: false },
      { text: 'The precise distance traveled by a delivery truck.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c06-0400-0000-0000-000000000000',
    question: 'What are the mean (μ) and standard deviation (σ) of the Standard Normal Distribution (Z-distribution)?',
    explanation: 'Standardized Z-distributions scale any normal curve to mean μ = 0 and standard deviation σ = 1.',
    options: [
      { text: 'Mean = 0, Standard Deviation = 1', is_correct: true },
      { text: 'Mean = 100, Standard Deviation = 15', is_correct: false },
      { text: 'Mean = 1, Standard Deviation = 0', is_correct: false },
      { text: 'Mean = 50, Standard Deviation = 10', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c06-0600-0000-0000-000000000000',
    question: 'A test score has a Z-score of +2.0. What does this indicate?',
    explanation: 'A Z-score measures how many standard deviations an observation lies above (+) or below (-) the mean.',
    options: [
      { text: 'The score is 2 standard deviations above the population mean.', is_correct: true },
      { text: 'The score is 2% higher than the average score.', is_correct: false },
      { text: 'The student failed the test by 2 points.', is_correct: false },
      { text: 'The score is equal to the median score.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c06-0700-0000-0000-000000000000',
    question: 'Which distribution best models the number of website visits occurring in a fixed 1-hour time window?',
    explanation: 'The Poisson distribution models the count of events occurring within a fixed interval of time or space.',
    options: [
      { text: 'Poisson Distribution', is_correct: true },
      { text: 'Binomial Distribution', is_correct: false },
      { text: 'Uniform Distribution', is_correct: false },
      { text: 'Normal Distribution', is_correct: false }
    ]
  },

  // Module 7
  {
    lesson_id: 'f0206c07-0100-0000-0000-000000000000',
    question: 'Why is Simple Random Sampling considered a gold standard in survey analytics?',
    explanation: 'Random selection ensures every member has an equal non-zero probability of being sampled.',
    options: [
      { text: 'Every individual in the population has an equal chance of selection, minimizing bias.', is_correct: true },
      { text: 'It guarantees that the sample size will equal the population size.', is_correct: false },
      { text: 'It costs zero dollars to implement.', is_correct: false },
      { text: 'It eliminates the need for statistical inference.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c07-0400-0000-0000-000000000000',
    question: 'Conducting an online-only survey to measure overall national opinions risks which type of bias?',
    explanation: 'Omitting non-internet users creates selection bias, making the sample unrepresentative of the broader population.',
    options: [
      { text: 'Selection/Coverage Bias (excluding citizens without internet access)', is_correct: true },
      { text: 'Response Rate Inflation', is_correct: false },
      { text: 'Central Limit Fallacy', is_correct: false },
      { text: 'Measurement Calibration Bias', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c07-0600-0000-0000-000000000000',
    question: 'What happens to the Standard Error of the mean as sample size (n) increases?',
    explanation: 'SE = σ / sqrt(n). Larger sample sizes reduce sample variability around the population mean.',
    options: [
      { text: 'Standard Error decreases, increasing estimate precision.', is_correct: true },
      { text: 'Standard Error increases proportionally.', is_correct: false },
      { text: 'Standard Error remains unchanged regardless of sample size.', is_correct: false },
      { text: 'Standard Error becomes equal to the population variance.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c07-0700-0000-0000-000000000000',
    question: 'According to the Central Limit Theorem, what shape does the sampling distribution of the mean take for large samples (n ≥ 30), regardless of the underlying population shape?',
    explanation: 'CLT states that the distribution of sample means approaches normality as sample size grows sufficiently large.',
    options: [
      { text: 'Normal Distribution (bell-shaped)', is_correct: true },
      { text: 'Uniform Distribution', is_correct: false },
      { text: 'Exponential Distribution', is_correct: false },
      { text: 'Bimodal Distribution', is_correct: false }
    ]
  },

  // Module 8
  {
    lesson_id: 'f0206c08-0100-0000-0000-000000000000',
    question: 'In an A/B test comparing a new website checkout button against the existing button, what does the Null Hypothesis (H0) state?',
    explanation: 'H0 represents the baseline status quo assumption of "no effect" or "no difference."',
    options: [
      { text: 'There is no significant difference in conversion rates between the new and existing buttons.', is_correct: true },
      { text: 'The new button increases conversion rates significantly.', is_correct: false },
      { text: 'The existing button is 100% defective.', is_correct: false },
      { text: 'Both buttons will have 0% conversion.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c08-0300-0000-0000-000000000000',
    question: 'If an analyst sets significance level α = 0.05 and obtains a p-value of 0.02, what decision should be made?',
    explanation: 'When p-value ≤ α, observed data is unlikely under H0, so we reject H0.',
    options: [
      { text: 'Reject the Null Hypothesis (p < α indicates statistically significant evidence).', is_correct: true },
      { text: 'Fail to reject the Null Hypothesis.', is_correct: false },
      { text: 'Accept the Null Hypothesis as 100% proven true.', is_correct: false },
      { text: 'Discard the data and restart the test.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c08-0500-0000-0000-000000000000',
    question: 'What is a Type I error (false positive) in hypothesis testing?',
    explanation: 'Type I error occurs when we conclude an effect exists when in reality it does not (false alarm).',
    options: [
      { text: 'Rejecting a true Null Hypothesis', is_correct: true },
      { text: 'Failing to reject a false Null Hypothesis', is_correct: false },
      { text: 'Setting alpha to 0.01 instead of 0.05', is_correct: false },
      { text: 'Making a calculation mistake in computing the mean', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c08-0600-0000-0000-000000000000',
    question: 'Which statistical test is appropriate for comparing the average monthly spend between two independent customer groups (e.g., Mobile Users vs Desktop Users)?',
    explanation: 'Independent two-sample t-tests compare continuous numerical means across two groups.',
    options: [
      { text: 'Two-Sample Independent T-Test', is_correct: true },
      { text: 'Chi-Square Test of Independence', is_correct: false },
      { text: 'Linear Regression Analysis', is_correct: false },
      { text: 'One-Way ANOVA', is_correct: false }
    ]
  },

  // Module 9
  {
    lesson_id: 'f0206c09-0100-0000-0000-000000000000',
    question: 'Which chart type is best suited for visually inspecting the relationship between two continuous numerical variables?',
    explanation: 'Scatter plots display paired numeric observations as points on X and Y axes.',
    options: [
      { text: 'Scatter Plot', is_correct: true },
      { text: 'Pie Chart', is_correct: false },
      { text: 'Bar Chart', is_correct: false },
      { text: 'Donut Chart', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c09-0200-0000-0000-000000000000',
    question: "What is the valid numerical range of Pearson's correlation coefficient (r)?",
    explanation: "Pearson's r is bounded between -1 (perfect negative linear relationship) and +1 (perfect positive linear relationship).",
    options: [
      { text: '-1.0 to +1.0', is_correct: true },
      { text: '0.0 to +1.0', is_correct: false },
      { text: '-100 to +100', is_correct: false },
      { text: '0 to infinity', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c09-0500-0000-0000-000000000000',
    question: 'A correlation coefficient r = -0.85 between product price and sales volume indicates:',
    explanation: 'Negative r indicates inverse movement, and magnitude 0.85 indicates strong linear correlation.',
    options: [
      { text: 'A strong negative linear relationship (as price increases, sales volume tends to decrease).', is_correct: true },
      { text: 'A weak positive relationship.', is_correct: false },
      { text: 'That price changes cause exactly 85% of sales drops.', is_correct: false },
      { text: 'No linear relationship exists.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c09-0700-0000-0000-000000000000',
    question: 'Ice cream sales and swimming pool accidents both rise during summer. What explains this correlation?',
    explanation: 'Confounding variables can create spurious correlations between unrelated variables.',
    options: [
      { text: 'A third confounding variable (summer temperature/weather) influences both.', is_correct: true },
      { text: 'Eating ice cream directly causes swimming pool accidents.', is_correct: false },
      { text: 'Swimming pool accidents cause people to buy ice cream.', is_correct: false },
      { text: 'Correlation always proves causation.', is_correct: false }
    ]
  },

  // Module 10
  {
    lesson_id: 'f0206c0a-0100-0000-0000-000000000000',
    question: 'What is the primary objective of Simple Linear Regression?',
    explanation: 'Linear regression models how a predictor variable X influences a target variable Y.',
    options: [
      { text: 'To model the linear relationship between an independent variable X and a dependent outcome Y for prediction.', is_correct: true },
      { text: 'To group customers into unlabelled clusters.', is_correct: false },
      { text: 'To count the total number of rows in a database table.', is_correct: false },
      { text: 'To calculate the median value of a single variable.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c0a-0200-0000-0000-000000000000',
    question: 'An analyst builds a model predicting Monthly Electricity Bill based on Household Size. What is the dependent variable (Y)?',
    explanation: 'The dependent variable Y is the outcome metric being predicted.',
    options: [
      { text: 'Monthly Electricity Bill', is_correct: true },
      { text: 'Household Size', is_correct: false },
      { text: 'Cost of Electricity per kWh', is_correct: false },
      { text: 'Square footage of the home', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c0a-0400-0000-0000-000000000000',
    question: 'In the regression equation Y = 15 + 3.5X, what does the slope (b = 3.5) represent?',
    explanation: 'The slope coefficient quantifies the expected change in outcome Y per unit change in predictor X.',
    options: [
      { text: 'For every 1-unit increase in X, Y is predicted to increase by 3.5 units.', is_correct: true },
      { text: 'The predicted value of Y when X equals 0.', is_correct: false },
      { text: 'The total correlation coefficient squared.', is_correct: false },
      { text: 'The standard error of the estimate.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c0a-0600-0000-0000-000000000000',
    question: 'What is a residual in linear regression analysis?',
    explanation: 'Residuals represent prediction errors for individual data points.',
    options: [
      { text: 'The difference between the actual observed value Y and the predicted value Ŷ (Residual = Y - Ŷ).', is_correct: true },
      { text: 'The total slope divided by the intercept.', is_correct: false },
      { text: 'The percentage of variance unexplained by X.', is_correct: false },
      { text: 'The highest outlier in the dataset.', is_correct: false }
    ]
  },

  // Module 11
  {
    lesson_id: 'f0206c0b-0100-0000-0000-000000000000',
    question: 'Before performing complex statistical modeling on business data, what is the mandatory first step?',
    explanation: 'Exploratory data audit ensures dataset cleanliness and validity before modeling.',
    options: [
      { text: 'Conduct data quality audits, check missing values, and verify data types.', is_correct: true },
      { text: 'Immediately publish results to executives.', is_correct: false },
      { text: 'Delete all rows with zero values without inspection.', is_correct: false },
      { text: 'Run a complex deep learning neural network.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c0b-0300-0000-0000-000000000000',
    question: 'Why do data analysts create summary statistics and histograms during initial EDA?',
    explanation: 'Exploratory Data Analysis (EDA) reveals core data characteristics and guides subsequent analytical modeling.',
    options: [
      { text: 'To understand data central tendency, spread, skewness, and identify anomalies.', is_correct: true },
      { text: 'To replace formal hypothesis testing entirely.', is_correct: false },
      { text: 'To increase the database storage efficiency.', is_correct: false },
      { text: 'To format spreadsheet table borders.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c0b-0600-0000-0000-000000000000',
    question: 'In an e-commerce case study, an analyst tests whether a 5% discount banner increases checkout completion. Why is statistical testing necessary?',
    explanation: 'Hypothesis testing provides empirical proof that business metric changes reflect true underlying signals.',
    options: [
      { text: 'To confirm that the observed lift is statistically significant and not random noise.', is_correct: true },
      { text: 'To guarantee that every customer makes a purchase.', is_correct: false },
      { text: 'To calculate the exact tax rate on purchases.', is_correct: false },
      { text: 'Because marketing rules require approval from a statistician.', is_correct: false }
    ]
  },
  {
    lesson_id: 'f0206c0b-0800-0000-0000-000000000000',
    question: 'When presenting statistical findings to non-technical executive stakeholders, what is the best practice?',
    explanation: 'Data analysts must bridge the gap between quantitative rigor and strategic business decision-making.',
    options: [
      { text: 'Translate p-values and Z-scores into clear business outcomes, financial impacts, and actionable recommendations.', is_correct: true },
      { text: 'Show raw code scripts and raw SQL output tables without context.', is_correct: false },
      { text: 'Hide all data and use only intuition.', is_correct: false },
      { text: 'Focus exclusively on complex mathematical derivation proofs.', is_correct: false }
    ]
  }
];

// Map of processed checkpoints with deterministic UUIDs
export const checkpointsMap: Record<string, LessonCheckpoint> = {};

rawCheckpoints.forEach((raw) => {
  const cpId = uuidv5(`cp_${raw.lesson_id}`, NAMESPACE);
  let order = 1;
  const options: CheckpointOption[] = raw.options.map((opt) => ({
    id: uuidv5(`opt_${cpId}_${order}`, NAMESPACE),
    option_text: opt.text,
    is_correct: opt.is_correct,
    display_order: order++
  }));

  checkpointsMap[raw.lesson_id] = {
    id: cpId,
    lesson_id: raw.lesson_id,
    question: raw.question,
    question_type: 'SINGLE_CHOICE',
    explanation: raw.explanation,
    options
  };
});

const ATTEMPTS_TABLE = 'student_checkpoint_attempts';

/**
 * True when the failure means the attempts table has not been created yet
 * (migration 00009 not applied). Any other error is a real error.
 */
function isMissingTable(error: any): boolean {
  if (!error) return false;
  const msg = String(error.message || '');
  return error.code === 'PGRST205' || /Could not find the table/i.test(msg);
}

/** Postgres unique-violation: the learner already answered this question. */
function isDuplicate(error: any): boolean {
  return error?.code === '23505';
}

/**
 * Fallback store, used only while migration 00009 is unapplied. It is
 * per-instance and lost on cold start, so it cannot be relied on. It exists so
 * that deploying this code before running the migration degrades instead of
 * erroring for learners.
 */
const attemptsStoreFallback: StudentAttempt[] = attemptsStore;

/**
 * Deterministic per-learner option order.
 *
 * Every question in the bank stores its correct option first, so a fixed
 * display order let a learner score full marks by always choosing option A.
 * The order below is derived from (userId, checkpointId): stable across
 * refreshes for one learner, different between learners. The stored answer key
 * is untouched, and grading always resolves against is_correct server-side.
 */
function orderOptionsForUser(
  options: CheckpointOption[],
  userId: string,
  checkpointId: string
): CheckpointOption[] {
  const seedStr = userId + ':' + checkpointId;
  let seed = 0;
  for (let i = 0; i < seedStr.length; i++) seed = (seed * 31 + seedStr.charCodeAt(i)) >>> 0;
  // xorshift32 keeps the shuffle deterministic without adding a dependency.
  const next = () => {
    seed ^= seed << 13; seed >>>= 0;
    seed ^= seed >> 17;
    seed ^= seed << 5;  seed >>>= 0;
    return seed / 0x100000000;
  };
  const arr = options.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(next() * (i + 1));
    const t = arr[i]; arr[i] = arr[j]; arr[j] = t;
  }
  return arr.map((o, i) => ({ ...o, display_order: i + 1 }));
}

/** Read this learner's recorded attempt, if any. */
async function findAttempt(userId: string, checkpointId: string): Promise<StudentAttempt | null> {
  const { data, error } = await supabaseAdmin
    .from(ATTEMPTS_TABLE)
    .select('id,user_id,checkpoint_id,selected_option_id,is_correct,attempted_at')
    .eq('user_id', userId)
    .eq('checkpoint_id', checkpointId)
    .maybeSingle();

  if (error) {
    if (!isMissingTable(error)) {
      console.error('[checkpoint] attempt lookup failed:', error.message);
    }
    return attemptsStoreFallback.find(
      (a) => a.user_id === userId && a.checkpoint_id === checkpointId
    ) || null;
  }
  return (data as StudentAttempt) || null;
}

/**
 * Get checkpoint for student.
 *
 * Never returns is_correct or the explanation for an unanswered question:
 * those are revealed only once an answer has been permanently recorded.
 */
export async function getStudentCheckpoint(lessonId: string, userId: string) {
  const cp = checkpointsMap[lessonId];
  if (!cp) return null;

  const previousAttempt = await findAttempt(userId, cp.id);
  const answered = Boolean(previousAttempt);
  const correctOption = cp.options.find((o) => o.is_correct);

  return {
    id: cp.id,
    lesson_id: cp.lesson_id,
    question: cp.question,
    question_type: cp.question_type,
    options: orderOptionsForUser(cp.options, userId, cp.id).map((o) => ({
      id: o.id,
      option_text: o.option_text,
      display_order: o.display_order,
    })),
    // Authoritative lock flag. The UI must not offer another submission when
    // this is true, and the server rejects one regardless.
    answered,
    previousAttempt: previousAttempt
      ? {
          selected_option_id: previousAttempt.selected_option_id,
          is_correct: previousAttempt.is_correct,
          attempted_at: previousAttempt.attempted_at,
        }
      : null,
    // Revealed only after the answer has been committed.
    correct_option_id: answered ? correctOption?.id : undefined,
    explanation: answered ? cp.explanation : undefined,
  };
}

/**
 * Submit a checkpoint attempt.
 *
 * One scored response per question: the first submitted answer is final.
 * Correctness is resolved from the server's own option data, never from the
 * request, and the UNIQUE (user_id, checkpoint_id) constraint rejects any
 * second submission, so the browser cannot retry its way to a correct answer.
 */
export async function submitStudentAttempt(
  userId: string,
  lessonId: string,
  selectedOptionId: string
) {
  const cp = checkpointsMap[lessonId];
  if (!cp) return { success: false, error: 'No checkpoint found for this lesson.', status: 404 };

  const selectedOpt = cp.options.find((o) => o.id === selectedOptionId);
  if (!selectedOpt) return { success: false, error: 'Invalid option selected.', status: 400 };

  const correctOption = cp.options.find((o) => o.is_correct);
  const isCorrect = selectedOpt.is_correct === true;

  // Reject before writing when a recorded answer is already visible.
  const existing = await findAttempt(userId, cp.id);
  if (existing) {
    return {
      success: false,
      error: 'This question has already been answered. Each question allows one submission.',
      status: 409,
      already_answered: true,
      is_correct: existing.is_correct,
      selected_option_id: existing.selected_option_id,
      correct_option_id: correctOption?.id,
      explanation: cp.explanation,
    };
  }

  const row = {
    user_id: userId,
    checkpoint_id: cp.id,
    lesson_id: lessonId,
    selected_option_id: selectedOptionId,
    is_correct: isCorrect,
    attempted_at: new Date().toISOString(),
  };

  const { error } = await supabaseAdmin.from(ATTEMPTS_TABLE).insert(row);

  if (error) {
    // The constraint is the real guard against two concurrent submissions;
    // whichever loses is reported as already answered.
    if (isDuplicate(error)) {
      return {
        success: false,
        error: 'This question has already been answered. Each question allows one submission.',
        status: 409,
        already_answered: true,
        correct_option_id: correctOption?.id,
        explanation: cp.explanation,
      };
    }
    if (isMissingTable(error)) {
      console.warn('[checkpoint] attempts table missing; recording in memory only (apply migration 00009).');
      attemptsStoreFallback.push({ id: uuidv5('att_' + userId + '_' + cp.id, NAMESPACE), ...row });
    } else {
      console.error('[checkpoint] attempt insert failed:', error.message);
      return { success: false, error: 'Could not record your answer. Please try again.', status: 500 };
    }
  }

  return {
    success: true,
    is_correct: isCorrect,
    selected_option_id: selectedOptionId,
    correct_option_id: correctOption?.id,
    explanation: cp.explanation,
  };
}
